### ISSUE TITLE
Wallet performance: problematic RPC calls 

### ISSUE THREAD

**Issue by svk31** [BitShares/bitshares#1112]
I've been looking into the performance issues of the wallet and it seems to me they're in a large part related to the performance of three RPC calls:

wallet_account_balance
wallet_account_yield
blockchain_list_assets

While the use of these can definitely be optimized in the wallet (they're being called too often IMO through "Wallet.refresh_balances"), an optimization in the client would be very beneficial. 

With a wallet containing two accounts these calls take from 0.5s to 2s on my computer which has an SSD and an i5 CPU, I imagine older PCs and especially those using mechanical drives might take far longer.

**Comment by wackou** [comment]
Another API call that is kind of problematic is ``blockchain_get_delegate_slot_records``, which takes up to 2 full seconds, even if only asking for the last N blocks. I worked around it myself using some smart caching (ie: only needs to fetch this after a delegate produced a block), but it would be nice to have it faster in the client. Maybe it's possible to do a backwards search instead of starting from the first one, as it's more common to ask for the last N blocks rather than all of them.

**Comment by svk31** [comment]
Indeed, I actually already asked for an improvement in that call and Vikram made a fix for it(see #858), but the performance is still bad enough that I can't use it to include slot records information on bitsharesblocks. Reverse searching was one of the things Vikram added though, as well as a limit on the number of records returned.

**Comment by wackou** [comment]
oh ok, I was already using the limit on blocks returned, didn't realize it was that recent. This is better as you don't return all blocks (hence don't serialize them all) but it still needs to walk all the blocks in the client in normal order, which is what I imagine takes all the time. See this: 

https://github.com/BitShares/bitshares/commit/e947ccab07bc2fda7469b5401ad3ba129b93e047#diff-d3db8985f6cf8f5790e9a0c5d3ad2a72L2028

Maybe a reverse_iterator could help here, not sure if that's possible though.

In any case, there's only so much that can be done in the client, and we should strive to cache as much as possible (ie: you only really need to call ``blockchain_get_delegate_slot_records`` once every ~17mins for each delegate, which I'm doing now. Of course, you have all the delegates on bitsharesblocks, so that's not negligible)

I was thinking of making a "caching server" for the client, acting as a proxy to the client with all the same RPC calls, but caching the calls in a "smart" way. This is still way off and I haven't even started, so don't take my word for it, but maybe in a couple of weeks, who knows. So many ideas, so little time... :smile:

**Comment by vikramrajkumar** [comment]
I will take another look when I get back to this, but I believe the main limitation is that LevelDB doesn't provide fast reverse iteration i.e. it has to walk all records to the end first (and we don't keep a cache of this db in memory). But given the nature of the slot records, maybe it makes sense to store them in reverse order (newest first) to begin with--@svk31 @wackou does prioritizing newer slot records make more sense?

**Comment by svk31** [comment]
For my use case, definitely! I'll probably only ever use the last 100 or so records, so that would be an easy solution for me.

**Comment by wackou** [comment]
For me too, the main reason I use it is to be able to display either "last N blocks produced" or "last N blocks missed". I do first get all blocks (once) and cache them, then only get the last ones to update my cache, so this is the call I make a lot of times. relevant code is here:
https://github.com/wackou/bts_tools/blob/master/bts_tools/rpcutils.py#L283

Given that the call is expensive, I now cache it like here:
https://github.com/wackou/bts_tools/blob/master/bts_tools/rpcutils.py#L259

however, it'd still be nice to have the call be much faster. If it is a possibility to store the slots in reverse order in leveldb without impacting the insertion of a new slot (prepending instead of appending), then I would say it seems like a smart move.

While we're at it, a few more comments about ``blockchain_get_delegate_slot_records``:
 - the default values are ok most of the time, but can lead to weird behavior in some cases, such as during the "big forks" of 0.4.26/0.4.27, where delegate participation fell quite low and then

  ```
  blockchain_get_delegate_slot_records delegate
  ```
  which is really
  ```
  blockchain_get_delegate_slot_records delegate -1000 10
  ```
  returns nearly, but not all the last blocks (took me a while to figure that out). I would recommend to put as default values -1000 and 50 at least, so this would return 10 blocks on average usually but would return all the last blocks anyway unless delegate participation falls under ~20%. Or even -1000 and 1000

 - Another, much less important remark (but for the sake of completeness) is that the default value of -1000 gives some problems at the very beginning of a blockchain (happened to me with PTS-DPOS) because if you're at block number < 1000, then it subtract 1000 from that, ends up with a negative value, and fails.

**Comment by wackou** [comment]
actually, on the topic of default args for ``blockchain_get_delegate_slot_records``, I think it would make more sense to change the API call to be
```
blockchain_get_delegate_slot_records delegate_name count
```
where count is the number of blocks, but returned in reverse order (newest first). That way,
```
blockchain_get_delegate_slot_records delegate_name 10
```
always returns the last 10 blocks for a delegate, regardless of network participation, etc. For having all the blocks, you'd just need to pass a really huge value there.

**Comment by vikramrajkumar** [comment]
Optimize `wallet_account_balance` and `wallet_account_yield`: https://github.com/BitShares/bitshares/commit/8c87046384cdba3acde818b75a0eca885e41e852

`blockchain_list_assets` isn't going to get much faster, it's a heavy operation like doing `blockchain_list_accounts`. It just shouldn't be called very often.

**Comment by vikramrajkumar** [comment]
@svk31 @wackou `blockchain_get_delegate_slot_records` now follows the API described by @wackou above.

I've changed the databases to index by both delegate ID and reverse timestamp, so it should be faster now when querying recent records for a specific delegate. There should also no longer be weird behavior around forking events.

This change isn't targeted to hit `master` until 0.6; let me know if you still have problems after that.

**Comment by wackou** [comment]
thanks @vikramrajkumar !

**Comment by vikramrajkumar** [comment]
Also @svk31 @wackou I've just cleaned up the "track statistics" setting to disable some nonessential record updates by default (see https://github.com/BitShares/bitshares/commit/a63b1b806e896ab88fc98c3cf1d5c6b8e27091d1). In particular, to index slot records in the future, you will need to add `"statistics_enabled": true` to your `config.json` and reindex.
