### ISSUE TITLE
[network] client not reconnecting if network goes down 

### ISSUE THREAD

**Issue by xeroc** [BitShares/bitshares#1127]
When I suspend my laptop while running bts .. I obviously loose every single connection due to powerdown of wifi ..

when resuming session .. wifi goes up again and system reconnects to the internet ... but the client will not try to connect to the network .. stays at 0 connections indefinitely (it seems)

**Comment by vikramrajkumar** [comment]
@xeroc @btswildpig Does this still happen in newest versions?

**Comment by btswildpig** [comment]
Don't know if it's the exact case . 
It seems to be solved if you use this approach :
First open the 0.6.2 wallet , it says "connected' , then unplug my wifi , the connection is gone . Finally , I replug my wifi , the connection automatically back on line without needing to restart the wallet . 

I wonder if that's the case in "unstable wifi or unstable network " though ...because unplug and replug is cut and dry , easy to reconnect  ?

**Comment by xeroc** [comment]
all fine here .. thanks
