### ISSUE TITLE
How does FC serialize in binary json ( a "variant" type )?

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#1231]
In account registration, the public_data type is a "variant"...  This data is from a transaction and includes the json {"data":"value"}.  So far I can see that "data" and "value" just strings prefixed by a length (probably varint32).  Punctuation is not serialized.. 

The serialized json is shown as hex below starting with 07 and ending with 65
```
>>> wallet_account_register bob-8d02 delegate0 {"data":"value"}
07 0104 6461 7461 0505 7661 6c75 65  ...data..value
```
There are a number of low level classes and many steps in the code in FC.  Where might be the best place to start researching this?

https://github.com/BitShares/bitshares/blob/v0.4.28-dev1/libraries/blockchain/include/bts/blockchain/account_operations.hpp#L22

https://github.com/BitShares/BitShares-JS/issues/28

**Comment by emfrias** [comment]
I'm afraid it's only defined by the low-level functions inside fc; we need to reverse-engineer those to come up with the spec.  As you've probably seen, the code for serializing most data types is fc/io/raw.hpp and fc/io/raw_variant.hpp.  Starting from fc::raw::pack(Stream& s, const variant& v), you can trace down and see how things are written out.  Punctuation doesn't matter because the serialization is done directly from the internal representation of the json (a variant, which can be an entire tree made up of primitive types, key/value objects ("variant_object") and arrays ("variants" = vector<variant>).

```
  07 (variant::object_type) is written by pack(Stream& s, const variant& v) 
               via pack(Stream& s, const unsigned_int& v),
       indicates the value is actually an JSON object
    01 is written by pack(Stream& s, const variant_object& v) 
                 via pack(Stream& s, const unsigned_int& v),
         is the size of the object, one key-value pair.  
      Then pack(Stream& s, const variant_object& v) writes out a list of key-value pairs:
        first key is a string so it's written out by pack(Stream& s, const fc::string& v), which writes:
          04 length, written by pack(Stream& s, const unsigned_int& v), and
          64 61 74 61 ("data")
        then the first value, which is a variant.  So it's handled by pack(Stream& s, const variant& v) which writes:
          05 (variant::string_type), and calls down to pack(Stream& s, const fc::string& v) to write it out as above:
            05 length
            76 61 6c 75 ("value")         
```
That should be it.  I think the final '65' belongs to something else.

**Comment by emfrias** [comment]
I should also mention that when you serialize a structure like register_account_operation, it is serialized due to the FC_REFLECT macro defined at the bottom of the file near it.  That macro lists the name of the fields, and the FC_REFLECT macro generates code that writes each field out in order.  It's possible that there are some fields in the struct that aren't listed in the FC_REFLECT call -- in that case they won't get written serialized out.  It's also possible that they're listed in a different order in the FC_REFLECT call than they exist in the structure; in that case too, the FC_REFLECT call defines the order they'll be serialized.  From what I've seen, we do reflect all the fields in important blockchain structures and we write them out in the correct order, so you probably won't have to worry about it.  But if you see something that doesn't make sense, check that FC_REFLECT is doing what you think it is.

**Comment by jcalfee** [comment]
This is going to help so much, I really appreciate it.  I'll get this to market asap.. thank you.

**Comment by pmconrad** [comment]
> I think the final '65' belongs to something else,

The final 65 is the 'e' in 'value'.
