### ISSUE TITLE
0.5.0 blockchain_list_recently_registered_accounts returns empty ,why?

### ISSUE THREAD

**Issue by CurrencyMaster** [BitShares/bitshares#1268]
i use blockchain_list_recently_registered_accounts command to implement my api,now blockchain_list_recently_registered_accounts command returns empty, what can i do ?

**Comment by vikramrajkumar** [comment]
This was accidentally broken in 0.5.0; it will be fixed in 0.6.0 (see #1237).

Note that after 0.6.0, you will also need to put `statistics_enabled: true` in your `config.json`, or run with `--statistics-enabled` and reindex to enable this feature.

Also note that this feature is not robust against chain forks, and might show incorrect information when a fork switch occurs.
