### ISSUE TITLE
margin call price is 150%, not 200%

### ISSUE THREAD

**Issue by nmushegian** [BitShares/bitshares#1273]
https://bitsharestalk.org/index.php?topic=13453.0;topicseen

**Comment by vikramrajkumar** [comment]
@theoreticalbts Can you also confirm whether the 300% collateral claim is true, or whether it is actually 200%?

**Comment by theoreticalbts** [comment]
300% collateral is currently implemented.

I think the intent was always to make margin calls happen when the short side lost 1/2 of their capital, which occurs at 150% when the initial capital is 200% (as it was before the change to 300% / 30 days).

**Comment by nmushegian** [comment]
I think the intent now is to make 200% the call price since that is what is being advertised

**Comment by theoreticalbts** [comment]
NB, if we implement this, we'll have to grandfather existing shorts into their current margin call prices.  We don't want to be in the business of changing the terms of financial derivative instruments *after* people have already bought them.

We have to also consider partial covering.

**Comment by nmushegian** [comment]
Yes, only apply this for future shorts. I don't see why we have to consider partial covers if we do that.

**Comment by bytemaster** [comment]
Someone changed this back.  I remember very clearly using *3  /4 as the multiple in prior versions.

**Comment by vikramrajkumar** [comment]
*cough* https://github.com/BitShares/bitshares/commit/c7d7257c99ff1bce3efc02cc3160bd20cd5bcd13 *cough*

**Comment by vikramrajkumar** [comment]
Why was this returned back to 3/4 from 2/3 yet again: https://github.com/BitShares/bitshares/commit/211c5e17f4b2d53ebfd5504c6ff1c7cdf731d509#diff-aa03531d90e90a2437e8cba9b668e0ccR400

**Comment by bytemaster** [comment]
It wasn't changed back to 2/3... it still reads 3/4.

**Comment by theoreticalbts** [comment]
Yeah, turns out these are both wrong.  Suppose you're shorting 100K BTS combined with 50K BTS going long at $0.02 / BTS, the debt is $1000 and the collateral is 150K BTS.  The debt's BTS value at price `p` (where P is dollars per BTS, i.e. $0.02 / BTS) would be `debt_value(p) = debt / p`.  Then 300% initial collateralization can be expressed as:

    collateral = 3 * debt_value(initial_price)

If margin call happens at 200% collateralization level, you have

    collateral = 2 * debt_value(call_price)

which simplifies to `collateral = 2 * debt / call_price`, solving for `call_price` gives

    call_price = 2 * debt / collateral

In general when we have collateralization level of `L` percent, we have

       collateral = (L/100) * debt_value(call_price)
    -> call_price = (L/100) * debt / collateral
                  = (debt / collateral) / (100/L)
                  = (debt / (k * collateral))      where k = 100/L

Defining `call_collateral = collateral * k`, we have `call_price = debt / call_collateral` which is what's actually implemented in the code:

      call_collateral.amount *= <something>;
      call_collateral.amount /= <something else>;

`something / something else` should be `k`, for `L = 200%` we have `k = 1/2`.

**Comment by theoreticalbts** [comment]
So `k` is simply the debt-to-collateral ratio at margin call.  `k = 1/2` is desired (debt is 1/2 collateral).

I will call this `D2C_RATIO_NUMERATOR / D2C_RATIO_DENOMINATOR`

**Comment by theoreticalbts** [comment]
Ran through the numbers with current order book, this is definitely fixed.  Probably by 5fcfef13b0ca477fa4e1f8768ea4eb2805fdeb63

**Comment by abitmore** [comment]
To be simple, if one shorts 100K BTS combined with 50K BTS going long at $0.02 / BTS, how much should the call price be? It's $0.01 in bts/0.8.x or earlier, but $0.013 in bts/0.9.0 and bts/0.9.1
