### ISSUE TITLE
Verify BitUSD vs BitGLD in Unit Tests / Regression Tests

### ISSUE THREAD

**Issue by bytemaster** [BitShares/bitshares#1295]

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/bitshares/commit/164404a2755adb7c6ce313aa4c20d1c59d432483

**Comment by theoreticalbts** [comment]
This test crashes the client for me.  I get a failed `FC_ASSERT` in https://github.com/BitShares/bitshares/blob/164404a2755adb7c6ce313aa4c20d1c59d432483/libraries/cli/print_result.cpp#L972-985 which is coming from https://github.com/BitShares/bitshares/blob/164404a2755adb7c6ce313aa4c20d1c59d432483/tests/regression_tests/wallet_market_usd_vs_gold/alice.log#L12050

The code there doesn't check `if (status)`, causing dereference to fail.  The whole block looks like it should be wrapped in `if ( status.valid() )` but I am not sure what the proper action in the `else` would be, because I'm not sure of the semantics of what `status.valid()` actually means in that case.

**Comment by theoreticalbts** [comment]
I also suggest running `debug_enable_output false` before publishing feeds, and `debug_enable_output true` afterwards.  Just to make the size of the test log more manageable.

**Comment by vikramrajkumar** [comment]
At a quick look, `!status.valid()` would seem to mean that the market has yet to even be initialized (no orders and no feeds yet for that market pair).
