### ISSUE TITLE
Commit "Fix encrypted RPC on Linux" ignores return value

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1338]
Commit 02209911719b7ae3cd4fd8b2409c75a299f82913 needs to be revised.  The return value from `readsome()` is ignored.

For that matter, I'm not sure why this fix is necessary at all.

**Comment by nathanhourt** [comment]
It's necessary because stcp_socket asserts that the read is a multiple of 16 bytes. Reads later on seem not to bother it, but this one does. It's a dirty hack, which could be done more elegantly, but I needed something to work.

As to the retval of `readsome()`, I don't see why I need to care. There's no risk of using out of bounds memory here (unless fc::raw::unpack is horribly broken... so actually, there's some risk, but it's got nothing to do with readsome) and if anything other than 80 bytes comes over that wire, the connection can't be trusted and therefore the entire thing is free to error out. But it doesn't hurt to `FC_ASSERT` that `readsome()` returns 80.
