### ISSUE TITLE
Consider expanding max supply allowed for user-issued assets

### ISSUE THREAD

**Issue by dnotestein** [BitShares/bitshares#1340]
Currently at 10^9 precision, the max supply of a user-issued asset is 9999999.99999999. This means UIAs can't map 1-1 to many cryptocurrencies (including Bitcoin, for example). If there's no technical reason for this limitation, we should raise the limit I think.

**Comment by theoreticalbts** [comment]
The reason @bytemaster stated for this limitation is to stay within the 53-bit mantissa of doubles, which eases integration of other languages.  Also, doubles are used at some places in our code.  While my staunch opinion is that a financially oriented product like us should *never use doubles anywhere*, unfortunately the existing code does sometimes use doubles.

We would have to do a fair amount of auditing to change `BTS_MAX_SHARE_SUPPLY`, not least because I don't believe anyone anticipated ever changing it.  You could always set precision lower and use bits [1], or resign yourself to never being able to have more than 10 million UIA-BTC.

[1] Many bitcoin related websites use the word "bit" to refer to a micro-BTC, one millionth of a bitcoin.

**Comment by vikramrajkumar** [comment]
Note that no state transitions depend on doubles/floats, and any usage of them in the code is purely for convenience and can be changed without a fork. In some cases, they cause user-facing precision issues (e.g. when entering decimals in the API), and very much need to be changed.

**Comment by vikramrajkumar** [comment]
Too low priority; shelving for now unless we get some demand for it.
