### ISSUE TITLE
Random Shuffle Skipping every 5th delegate

### ISSUE THREAD

**Issue by bytemaster** [BitShares/bitshares#1348]
for( uint32_t i = 0; i < num_del; ++i )
          {
            ////first time,here,i==0;the second time,for start i==5
             for( uint32_t x = 0; x < 4 && i < num_del; ++x, ++i )
                std::swap( active_del[ i ], active_del[ rand_seed._hash[ x ] % num_del ] );
             rand_seed = fc::sha256::hash( rand_seed );
          }  
         ////look,first

**Comment by theoreticalbts** [comment]
The revised implementation in 9fccd16 is *still not correct*.  First, your pre-increment operator in the inner loop still looks wrong.  Second, you are effectively picking from all delegates.  For an explanation of why this is biased, see http://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle#Implementation_errors -- basically the idea is that picking from all candidates gives you n^n different choices based on what your source of randomness says.  You want to choose evenly from n! permutations, but an algorithm with n^n different random choices can't possibly work because n! does not divide n^n.

I've re-written the shuffle algorithm to be correct, and incidentally refactored the code to be much more readable.

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/bitshares/commit/70170e8719dbe27f3b848c0319727ccee2ecd2d6
