### ISSUE TITLE
Transaction builder: deposit_asset still references payer's owner key

### ISSUE THREAD

**Issue by jcalfee** [BitShares/bitshares#1367]
As do other deposit methods...

**Comment by vikramrajkumar** [comment]
It seems to be used only for internal balance tracking, memo signing, and record labeling. Why does it matter?

**Comment by jcalfee** [comment]
I think I made an assumption.  Can you spend (sign) using the current active key a deposit made to the owner key?  In that case, it makes more sense to always send to the owner key so simplifies getting and spending balance records.

**Comment by jcalfee** [comment]
We can discuss soon enough.  I'll just close this one.. thanks

**Comment by theoreticalbts** [comment]
> Can you spend (sign) using the current active key a deposit made to the owner key?

No.  Recall an address is the hash of a key.  At the blockchain level, senders send to addresses, not accounts.  It is up to the sender's wallet to decide which of the receiver's keys to send to!  Of course, if the user tells your wallet "I am sending to btercom account," then the wallet should look up the current active key for btercom account and send to it.

There is nothing at the blockchain level to prevent the user sending to the owner address or any previous active key's address for the target account.  The only thing preventing such transfers is an understanding that wallets SHOULD always send to the current active key.  Since the receiving account may not be expecting to receive funds from a malfunctioning wallet, old active keys and owner keys may not do TITAN scanning (and in the case of owner key may be in cold storage).

This also means that if you plan to create a new active key and delete the old active key, you must transfer your entire balance to the new key's address before you delete the old key.  Otherwise you will lose access to that old balance when you change your key!

The official wallet does not support deletion of old keys, so this is not a huge concern for us.

**Comment by theoreticalbts** [comment]
To get back to the original bug, if Bob transfers to Alice when she has owner key == active key, then Alice's balance will be owned by her owner address.  Even after Alice changes her active key, that balance will still be owned by her owner key.

So if Alice sends back to Bob, Alice will have to use her owner key to unlock the balance.

Does this sound like the scenario you're seeing?

**Comment by jcalfee** [comment]
Not quite .. But I do look forward to meeting you when I am in town Feb 18-24.  There are many angles, maybe we will get to discuss them at that time..
