### ISSUE TITLE
Test expired AND called cover

### ISSUE THREAD

**Issue by theoreticalbts** [BitShares/bitshares#1370]
We want to be very sure this is correctly handled as it seems like an error-prone corner case.  Keep in mind collection classes (and maybe LevelDB) may have problems with concurrent modification of iterators.  I think we may need to referentially specify cover orders in this case.

**Comment by vikramrajkumar** [comment]
Please note that all LevelDB iterators are *const* iterators. Do not use them for modification.

**Comment by theoreticalbts** [comment]
The problem is we need two iterators to walk covers by call price and expiration.  This ticket is just to remind me that if we don't explicitly handle the behavior (and write a test to make sure that the handling is correct), quite conceivably an order that's both margin called *and* expired simultaneously could end up either being filled twice, or yanked out of a collection that has a live iterator (the documentation of most languages' collection frameworks has big red BEWARE UNDEFINED BEHAVIOR warnings when it comes to modifying collections that have active iterators).

**Comment by vikramrajkumar** [comment]
I'm not familiar with the new market engine, but note that it should never modify any LevelDB, and all state changes (including index updates) need to be staged to the pending state.

Relatedly, note that @bytemaster's implementation of the new short indexes in https://github.com/BitShares/bitshares/commit/d076871b8e74efae4e69a535b96da392f8ea73f3 and https://github.com/BitShares/bitshares/commit/b37671d64f03c4993eff4f20604c5267f458d381 is incorrect, because it is modifying the chain state directly instead of the pending state--making it so those changes cannot be rewound. I have left that as-is for now while you guys develop, until we have time to sit down and think about how to do it correctly.

**Comment by theoreticalbts** [comment]
Thanks for bringing this up.  I'll fix it.

**Comment by bytemaster** [comment]
Actually, my implementation is not incorrect.   The feed records are all managed by the pending state so when ever you "undo" a store feed record it should revert the indexes.   You will note that the index values are ONLY changing within chain database.   So it doesn't need to be fixed.

**Comment by vikramrajkumar** [comment]
@theoreticalbts @bytemaster Upon review I think the original indexing is not as problematic as I thought. It is viable to modify indexes on store like that if they are not needed until the next block, which always the case here since the market runs before feed updates are evaluated. However, there still seem to be some issues:
- The `market_status` db is directly modified in an unrewindable way
- There are not corresponding index updates for `remove<feed_record>`
- `get_active_feed_price` is expensive, and this indexing looks generally expensive as well. I would wager that feed updates are by far the most common operation on the network, so the indexing should be done once at the end of applying the block for all dirty assets, rather than for *every* store that happens.

**Comment by theoreticalbts** [comment]
- if they are "fully" reindexed always, then they should work for arbitrary stores

Rewinding the main order table as needed and rebuilding all order indexes in every block is a workable approach, but horribly inefficient.

- the indexing should be done once at the end of applying the block for all dirty assets

A feed movement can cause a clean market to become dirty -- e.g. relative order moving into territory where it overlaps another order, a margin call being triggered when there's already an overlapping order that can fill it, or a short at the feed moving into an existing order.

I definitely agree that all feed updates in a block should be queued and executed in a batch at a single point in the processing of the block.  Furthermore we only need to reindex / dirty markets when a feed update actually results in changing the median value.

But hold off on this for another day or so, I'm pretty deep into patching it now.

**Comment by vikramrajkumar** [comment]
> A feed movement can cause a clean market to become dirty

Yes I should have been more clear--I indeed meant any assets which are now "dirty" due to feed updates, not the currently existing "dirty markets" notion that the code already uses for deciding when to execute the market engine.

**Comment by theoreticalbts** [comment]
MC test has it.
