### ISSUE TITLE
limit the maximal length of messages on wall

### ISSUE THREAD

**Issue by jimewu** [BitShares/bitshares#1371]
Right now you can directly burn a book on the wall using just 1 BTS.
For example: 
https://bitsharesblocks.com/accounts/account?name=btsbravo

**Comment by theoreticalbts** [comment]
What we really need is a transaction fee per KB.

**Comment by jimewu** [comment]
Great idea!

**Comment by nathanhourt** [comment]
The length is currently limited by the max transaction size. We've considered a dynamic fee per KB, but I believe we've always regarded it as being more complex than the value it provides is worth.

**Comment by jimewu** [comment]
Another concern is that if i can dump huge message on someone's  wall with very low costs,  I can easily make the wall of some account unusable.

**Comment by theoreticalbts** [comment]
We need a way to limit the *displayed characters* of a wall in bitsharesblocks (or the wallet).

**Comment by VoR0220** [comment]
I think the solution is worth pursuing. Pardon my ignorance, I'm new here. Why would this be more complex than the value it is worth? It sounds like a great solution.

**Comment by nathanhourt** [comment]
The fees are intended to be dynamic. As the value of BitShares changes, the current default fee of .5 BTS may become undesirable, and the fee would need to be changed. Optimally, delegates will publish the required fees, but if the fee is based on a function rather than a fixed amount, they would need to publish a function which would have to be evaluated, and then reaching consensus on what exactly the fee for any given transaction should be would become a difficult problem.

While it may be a nice feature, currently we've got higher priority tasks to deal with than making a dynamic fee and doing away with the transaction size limit.

**Comment by VoR0220** [comment]
hmmmm....keep this issue open. I would like to work on it in my spare time. I'm still learning my way around the code, but it seems like something that could be a really neat addition.
