### ISSUE TITLE
You can bypass locked screen simply by right click and "go back"

### ISSUE THREAD

**Issue by btswildpig** [BitShares/bitshares#1469]
0.7.0 bug

**Comment by xeroc** [comment]
you actually cannot do any harm by that because the wallet is locked and no private keys can be accessed .. though the balance and transaction history .. which you could also achieve by loading the wallet into the CLI and open it without unlocking it ..

TL;DR; the screen lock may be bypassed .. the locked privates keys are not

**Comment by vikramrajkumar** [comment]
Duplicate: https://github.com/BitShares/qt_wallet/issues/70
