### ISSUE TITLE
Wallet keeps on crashing on me.

### ISSUE THREAD

**Issue by rgcrypto** [BitShares/bitshares#1496]
After about 5 minutes of being open, the wallet makes everything on my computer crash. I run on windows 7.

The wallet crashed before I get to see anything from the market engine.

**Comment by Troglodactyl** [comment]
How much ram do you have?  By "everything" do you mean it freezes, or other applications spontaneously crash?  Is this issue new for you in the current version, or is this the first version you've used?

If haven't been able to get synced yet because of this, try running the bitshares_client from the install directory.  That's the core client without the GUI.  Just let it run until it syncs, you don't need to login or anything, and then close it and try running the GUI again.  If you try this please update this issue and let us know if it worked.

**Comment by vikramrajkumar** [comment]
Duplicate: #1477
