### ISSUE TITLE
Protect wallet directory with UNIX account permissions

### ISSUE THREAD

**Issue by drltc** [BitShares/bitshares#856]
On OS's where the functionality is available, we should `chmod 700` wallet directories by default.

**Comment by theoreticalbts** [comment]
Fixed by 4085e808523d1eed12166d0dfb571706d4370b88

According to https://bitsharestalk.org/index.php?topic=12780 we need to protect `config.json` as well since it may contain RPC credentials.  Since you can dump private keys over RPC, protecting the RPC credentials on a multi-user system is just as important as protecting the keys / wallet directory.  So I just set the permissions for the whole directory to `700`.

This is only done for a new data directory, so if the user wants more permissive access, they can simply `chmod` the directory appropriately.  It may also be useful to create the directory with `mkdir -p` before the first run.
